CREATE TABLE IF NOT EXISTS public.average_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec VARCHAR(255),
    d1 VARCHAR(50),
    d2 VARCHAR(50),
    dia VARCHAR(50),
    thick VARCHAR(50),
    avg_order_month_3 DECIMAL(12, 3),
    avg_order_month_6 DECIMAL(12, 3),
    avg_order_month_12 DECIMAL(12, 3),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.average_order ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for average_order" ON public.average_order FOR ALL USING (true);
