CREATE TABLE down_grade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL,
  work_center TEXT,
  problem TEXT,
  keterangan TEXT,
  qty_dg_pcs NUMERIC DEFAULT 0,
  qty_dg_kg NUMERIC DEFAULT 0,
  qty_reject_mtr NUMERIC DEFAULT 0,
  qty_reject_kg NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
